{
    "reviews": {
        "count":5,
        "first_item": {
            "id":10498509,
            "content": "Dupa 1 luna, inca rezista.",
            "user": {
                "id":3768936,
                "hash":"bf24722cdb6f0c74a70d3c04f19c81163768936032",
                "name":"Gabriel Suta Noje",
                "user_avatar":{
                    "initials":"GS",
                    "path":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131","background_color":"#009688","image": {
                        "original":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131",
                        "resized_images": [
                            {
                                "size":"40x40",
                                "url":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131?sz=40"
                            },
                            {
                                "size":"54x54",
                                "url":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131?sz=78"
                            }
                            ]
                        }
                    },
                "nickname":"",
                "url": {
                    "path":"\/product-feedback\/user-profile\/bf24722cdb6f0c74a70d3c04f19c81163768936032",
                    "desktop_base":"https:\/\/www.emag.ro","mobile_base":"https:\/\/www.emag.ro"
                },
                "is_official":false
            },
            "is_active": true,
            "moderation_status":"moderated_accepted",
            "created":"2024-06-27T14:16:24+00:00",
            "modified":"2024-06-27T14:16:24+00:00",
            "published":"2024-07-12T09:53:07+00:00",
            "deleted":"2024-07-12T09:53:07+00:00",
            "report_reason":"",
            "report_reason_description":"",
            "edit_url":{
                "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10498509\/edit",
                "desktop_base":"https:\/\/www.emag.ro",
                "mobile_base":"https:\/\/www.emag.ro"
            },
            "view_url":{
                "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10498509",
                "desktop_base":"https:\/\/www.emag.ro",
                "mobile_base":"https:\/\/www.emag.ro"
            },
            "type":"REVIEW",
            "title":"Super",
            "product":{
                "id":64743307,
                "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                "part_number_key":"DQ1T3KYBM",
                "image":{
                    "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                    "resized_images":[
                        {
                            "size":"80x80",
                            "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                        },
                        {
                            "size":"130x130",
                            "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                        },
                        {
                            "size":"300x300",
                            "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                        },
                        {
                            "size":"450x450",
                            "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                        }
                    ]
                },
                "family_characteristics":{
                    "name":"main",
                    "characteristics":[
                        {
                            "id":5401,
                            "name":"Culoare",
                            "value":{
                                "id":7374087,
                                "value":"Albastru"
                            },
                            "order":0
                        }
                    ]
                },
                "offer":{
                    "id":158121094,
                    "price":{
                        "current":100,
                        "is_min":false,
                        "is_max":false,
                        "legal":0,
                        "prefix":"Empty prefix",
                        "suffix":"Empty suffix Lei",
                        "is_visible":true,
                        "discount":{
                            "type":"percent",
                            "absolute":10,
                            "percent":9,
                            "is_special":false,
                            "is_visible":false,
                            "is_restricted_from_view":true,
                            "is_max":false,
                            "label":"Diferen\u021b\u0103:",
                            "labeled_as_discount":false
                        },
                        "currency":{
                            "id":23,
                            "name":{
                                "default":"RON",
                                "display":"Lei"
                            }
                        },
                        "net":84.03,
                        "recommended_retail_price":{
                            "amount":0,
                            "is_visible":false,
                            "label":"PRP:",
                            "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                        },
                        "lowest_price_30_days":{
                            "amount":0,
                            "is_visible":false,
                            "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                        },
                        "initial":100
                    },
                    "flags":{
                        "is_main":true,
                        "is_used":false,
                        "is_sales":false,
                        "is_active":true,
                        "has_discount":true,
                        "may_be_ordered":true,
                        "has_ecredit":false,
                        "has_bundles":false,
                        "has_gifts":false,
                        "has_bundle_first":false,
                        "is_self_source":false,
                        "has_warranty":false,
                        "has_badges":false,
                        "is_visible":true,
                        "has_services":false,
                        "has_buyback":false,
                        "has_buyback_v2":false,
                        "has_two_hour_delivery":false,
                        "has_same_day_delivery":false,
                        "has_three_hour_delivery":false,
                        "has_free_delivery":false,
                        "has_delivery_estimate":true,
                        "has_pickup":false,
                        "has_unified_badges":false,
                        "has_loyalty_points":false,
                        "has_banners":false,
                        "is_fulfilment_by_emag":false,
                        "show_legal_price":false,
                        "has_free_return":false,
                        "is_open_package":true,
                        "is_bf":false,
                        "has_campaign_badge":true,
                        "has_visible_badge_border":false,
                        "is_custom_discount":false,
                        "has_unfair_price":false,
                        "is_genius_eligible":true,
                        "genius_eligibility_type":2,
                        "has_courier_6h_delivery":false,
                        "only_in_showroom":false,
                        "is_adult_only":false
                    }
                },
                "url":{
                    "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
            },
            "content_no_tags":"Dupa 1 luna, inca rezista.",
            "moderated_by":"valentin.stan@emag.ro",
            "rating":5,
            "is_bought":true,
            "votes":0,
            "current_customer_has_voted":false,
            "brand_id":655277,
            "category_id":815,
            "review_characteristics":{
                "items_count":0
            },
            "offer_id":158121094,
            "client_type":"Review cumparator eMAG",
            "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.",
            "product_doc_id":64743307,
            "product_family_id":4057953
        },
        "items":[
            {
                "id":10498509,
                "content":"Dupa 1 luna, inca rezista.",
                "user":{
                    "id":3768936,
                    "hash":"bf24722cdb6f0c74a70d3c04f19c81163768936032",
                    "name":"Gabriel Suta Noje",
                    "user_avatar":{
                        "initials":"GS",
                        "path":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131",
                        "background_color":"#009688",
                        "image":{
                            "original":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131",
                            "resized_images":[
                                {
                                    "size":"40x40",
                                    "url":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131?sz=40"
                                },
                                {
                                    "size":"54x54",
                                    "url":"https:\/\/lh3.googleusercontent.com\/-JznW-ZBA1xM\/AAAAAAAAAAI\/AAAAAAAAAC8\/am7yho7T7Qc\/photo.jpg\u0026date=20171112221131?sz=78"
                                }
                            ]
                        }
                    },
                    "nickname":"",
                    "url":{
                        "path":"\/product-feedback\/user-profile\/bf24722cdb6f0c74a70d3c04f19c81163768936032",
                        "desktop_base":"https:\/\/www.emag.ro","mobile_base":"https:\/\/www.emag.ro"
                    },
                    "is_official":false
                },
                "is_active":true,
                "moderation_status":"moderated_accepted",
                "created":"2024-06-27T14:16:24+00:00",
                "modified":"2024-06-27T14:16:24+00:00",
                "published":"2024-07-12T09:53:07+00:00",
                "deleted":"2024-07-12T09:53:07+00:00",
                "report_reason":"",
                "report_reason_description":"",
                "edit_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10498509\/edit",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "view_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10498509",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "type":"REVIEW",
                "title":"Super",
                "product":{
                    "id":64743307,
                    "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                    "part_number_key":"DQ1T3KYBM",
                    "image":{
                        "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                        "resized_images":[
                            {
                                "size":"80x80",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                            },
                            {
                                "size":"130x130",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                            },
                            {
                                "size":"300x300",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                            },
                            {
                                "size":"450x450",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                            }
                        ]
                    },
                    "family_characteristics":{
                        "name":"main",
                        "characteristics":[
                            {
                                "id":5401,
                                "name":"Culoare",
                                "value":{
                                    "id":7374087,
                                    "value":"Albastru"
                                },
                                "order":0
                            }
                        ]
                    },
                    "offer":{
                        "id":158121094,
                        "price":{
                            "current":100,
                            "is_min":false,
                            "is_max":false,
                            "legal":0,
                            "prefix":"Empty prefix",
                            "suffix":"Empty suffix Lei",
                            "is_visible":true,
                            "discount":{
                                "type":"percent",
                                "absolute":10,
                                "percent":9,
                                "is_special":false,
                                "is_visible":false,
                                "is_restricted_from_view":true,
                                "is_max":false,
                                "label":"Diferen\u021b\u0103:",
                                "labeled_as_discount":false
                            },
                            "currency":{
                                "id":23,
                                "name":{
                                    "default":"RON",
                                    "display":"Lei"
                                }
                            },
                            "net":84.03,
                            "recommended_retail_price":{
                                "amount":0,
                                "is_visible":false,
                                "label":"PRP:",
                                "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                            },
                            "lowest_price_30_days":{
                                "amount":0,
                                "is_visible":false,
                                "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                            },
                            "initial":100
                        },
                        "flags":{
                            "is_main":true,
                            "is_used":false,
                            "is_sales":false,
                            "is_active":true,
                            "has_discount":true,
                            "may_be_ordered":true,
                            "has_ecredit":false,
                            "has_bundles":false,
                            "has_gifts":false,
                            "has_bundle_first":false,
                            "is_self_source":false,
                            "has_warranty":false,
                            "has_badges":false,
                            "is_visible":true,
                            "has_services":false,
                            "has_buyback":false,
                            "has_buyback_v2":false,
                            "has_two_hour_delivery":false,
                            "has_same_day_delivery":false,
                            "has_three_hour_delivery":false,
                            "has_free_delivery":false,
                            "has_delivery_estimate":true,
                            "has_pickup":false,
                            "has_unified_badges":false,
                            "has_loyalty_points":false,
                            "has_banners":false,
                            "is_fulfilment_by_emag":false,
                            "show_legal_price":false,
                            "has_free_return":false,
                            "is_open_package":true,
                            "is_bf":false,
                            "has_campaign_badge":true,
                            "has_visible_badge_border":false,
                            "is_custom_discount":false,
                            "has_unfair_price":false,
                            "is_genius_eligible":true,
                            "genius_eligibility_type":2,
                            "has_courier_6h_delivery":false,
                            "only_in_showroom":false,
                            "is_adult_only":false
                        }
                    },
                    "url":{
                        "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
                },
                "content_no_tags":"Dupa 1 luna, inca rezista.",
                "moderated_by":"valentin.stan@emag.ro",
                "rating":5,
                "is_bought":true,
                "votes":0,
                "current_customer_has_voted":false,
                "brand_id":655277,
                "category_id":815,
                "review_characteristics":{
                    "items_count":0
                },
                "offer_id":158121094,
                "client_type":"Review cumparator eMAG",
                "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.",
                "product_doc_id":64743307,
                "product_family_id":4057953
            },
            {
                "id":10345643,
                "content":"Foarte multumita de produs",
                "user":{
                    "id":7591802,
                    "hash":"fb33ab586e5c15697c66e6488eaecd837591802032",
                    "name":"Bulea Iulia",
                    "user_avatar":{
                        "initials":"BI",
                        "background_color":"#9c27b0"
                    },
                    "nickname":"",
                    "url":{
                        "path":"\/product-feedback\/user-profile\/fb33ab586e5c15697c66e6488eaecd837591802032",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "is_official":false
                },
                "is_active":true,
                "moderation_status":"moderated_accepted",
                "created":"2024-05-24T11:42:04+00:00",
                "modified":"2024-05-24T11:42:04+00:00",
                "published":"2024-06-04T08:06:07+00:00",
                "deleted":"2024-06-11T08:46:49+00:00",
                "report_reason":"",
                "report_reason_description":"",
                "edit_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10345643\/edit",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "view_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10345643",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "type":"REVIEW",
                "title":"Foarte multumit",
                "product":{
                    "id":64743307,
                    "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                    "part_number_key":"DQ1T3KYBM",
                    "image":{
                        "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                        "resized_images":[
                            {
                                "size":"80x80",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                            },
                            {
                                "size":"130x130",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                            },
                            {
                                "size":"300x300",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                            },
                            {
                                "size":"450x450",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                            }
                        ]
                    },
                    "family_characteristics":{
                        "name":"main",
                        "characteristics":[
                            {
                                "id":5401,
                                "name":"Culoare",
                                "value":{
                                    "id":7374087,
                                    "value":"Albastru"
                                },
                                "order":0
                            }
                        ]
                    },
                    "offer":{
                        "id":158121094,
                        "price":{
                            "current":100,
                            "is_min":false,
                            "is_max":false,
                            "legal":0,
                            "prefix":"Empty prefix",
                            "suffix":"Empty suffix Lei",
                            "is_visible":true,
                            "discount":{
                                "type":"percent",
                                "absolute":10,
                                "percent":9,
                                "is_special":false,
                                "is_visible":false,
                                "is_restricted_from_view":true,
                                "is_max":false,
                                "label":"Diferen\u021b\u0103:",
                                "labeled_as_discount":false
                            },
                            "currency":{
                                "id":23,
                                "name":{
                                    "default":"RON",
                                    "display":"Lei"
                                }
                            },
                            "net":84.03,
                            "recommended_retail_price":{
                                "amount":0,
                                "is_visible":false,
                                "label":"PRP:",
                                "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                            },
                            "lowest_price_30_days":{
                                "amount":0,
                                "is_visible":false,
                                "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                            },
                            "initial":100
                        },
                        "flags":{
                            "is_main":true,
                            "is_used":false,
                            "is_sales":false,
                            "is_active":true,
                            "has_discount":true,
                            "may_be_ordered":true,
                            "has_ecredit":false,
                            "has_bundles":false,
                            "has_gifts":false,
                            "has_bundle_first":false,
                            "is_self_source":false,
                            "has_warranty":false,
                            "has_badges":false,
                            "is_visible":true,
                            "has_services":false,
                            "has_buyback":false,
                            "has_buyback_v2":false,
                            "has_two_hour_delivery":false,
                            "has_same_day_delivery":false,
                            "has_three_hour_delivery":false,
                            "has_free_delivery":false,
                            "has_delivery_estimate":true,
                            "has_pickup":false,
                            "has_unified_badges":false,
                            "has_loyalty_points":false,
                            "has_banners":false,
                            "is_fulfilment_by_emag":false,
                            "show_legal_price":false,
                            "has_free_return":false,
                            "is_open_package":true,
                            "is_bf":false,
                            "has_campaign_badge":true,
                            "has_visible_badge_border":false,
                            "is_custom_discount":false,
                            "has_unfair_price":false,
                            "is_genius_eligible":true,
                            "genius_eligibility_type":2,
                            "has_courier_6h_delivery":false,
                            "only_in_showroom":false,
                            "is_adult_only":false
                        }
                    },
                    "url":{
                        "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
                },
                "content_no_tags":"Foarte multumita de produs",
                "moderated_by":"valentin.stan@emag.ro",
                "rating":5,
                "is_bought":true,
                "votes":0,
                "comments":[
                    {
                        "id":10422833,
                        "content":"Bun\u0103 Iulia,\u003Cbr \/\u003E \u003Cbr \/\u003E Ne bucur\u0103m s\u0103 auzim c\u0103 e\u0219ti foarte mul\u021bumit\u0103 de varianta Albastru a tablei de desen magnetice.\u003Cbr \/\u003E \u003Cbr \/\u003E Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\u003Cbr \/\u003E \u003Cbr \/\u003E Echipa Innovators",
                        "user":{
                            "id":105498146,
                            "hash":"dfadb97cd35e536d23646c233faf77c6105498146032",
                            "name":"The Innovators",
                            "user_avatar":{
                                "initials":"TI",
                                "background_color":"#009688"
                            },
                            "nickname":"",
                            "url":{
                                "path":"\/product-feedback\/user-profile\/dfadb97cd35e536d23646c233faf77c6105498146032",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "is_official":true
                        },
                        "is_active":true,
                        "moderation_status":"moderated_accepted",
                        "created":"2024-06-10T15:05:26+03:00",
                        "modified":"2024-06-10T15:05:26+03:00",
                        "published":"2024-06-11T08:46:49+03:00",
                        "deleted":"",
                        "report_reason":"",
                        "report_reason_description":"",
                        "edit_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10345643\/comment\/10422833\/edit",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "view_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10345643\/comment\/10422833",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "type":"COMMENT",
                        "product":{
                            "id":64743307,
                            "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                            "url":{
                                "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "part_number_key":"DQ1T3KYBM"
                        },
                        "content_no_tags":"Bun\u0103 Iulia,\n \n Ne bucur\u0103m s\u0103 auzim c\u0103 e\u0219ti foarte mul\u021bumit\u0103 de varianta Albastru a tablei de desen magnetice.\n \n Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\n \n Echipa Innovators",
                        "moderated_by":"cerasela.maxim@emag.ro",
                        "parent_id":10345643,
                        "is_official":true
                    }
                ],
                "current_customer_has_voted":false,
                "brand_id":655277,
                "category_id":815,
                "review_characteristics":{
                    "items_count":0
                },
                "offer_id":158121094,
                "client_type":"Review cumparator eMAG",
                "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.","product_doc_id":64743307,"product_family_id":4057953
            },
            {
                "id":10306186,
                "content":"",
                "user":{
                    "id":8341840,
                    "hash":"4bd037b029482515f77c44d2f58ca5718341840032",
                    "name":"Raluca Ralu","user_avatar":{
                        "initials":"RR",
                        "path":"https:\/\/s13emagst.akamaized.net\/layout\/ro\/\/images\/avatars\/1691753307_8341840.png",
                        "background_color":"#999999",
                        "image":{
                            "original":"https:\/\/s13emagst.akamaized.net\/layout\/ro\/\/images\/avatars\/1691753307_8341840.png",
                            "resized_images":[
                                {
                                    "size":"40x40",
                                    "url":"https:\/\/s13emagst.akamaized.net\/layout\/ro\/\/images\/avatars\/1691753307_8341840.png?width=40\u0026height=40\u0026hash=0CE956D9C213FA70D6E20DE233A11E10"
                                },
                                {
                                    "size":"54x54",
                                    "url":"https:\/\/s13emagst.akamaized.net\/layout\/ro\/\/images\/avatars\/1691753307_8341840.png?width=78\u0026height=78\u0026hash=76403D3E6650DF30588A6B9180E814A3"
                                }
                            ]
                        }
                    },
                    "nickname":"",
                    "url":{
                        "path":"\/product-feedback\/user-profile\/4bd037b029482515f77c44d2f58ca5718341840032",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "is_official":false
                },
                "is_active":true,
                "moderation_status":"moderated_accepted",
                "created":"2024-05-15T22:27:41+00:00",
                "modified":"2024-05-15T22:27:41+00:00",
                "published":"2024-05-27T15:06:04+00:00",
                "deleted":"2024-05-27T15:06:04+00:00",
                "report_reason":"",
                "report_reason_description":"",
                "edit_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10306186\/edit",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "view_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10306186",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "type":"REVIEW",
                "title":"Recomand",
                "product":{
                    "id":64743307,
                    "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                    "part_number_key":"DQ1T3KYBM",
                    "image":{
                        "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                        "resized_images":[
                            {
                                "size":"80x80",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                            },
                            {
                                "size":"130x130",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                            },
                            {
                                "size":"300x300",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                            },
                            {
                                "size":"450x450",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                            }
                        ]
                    },
                    "family_characteristics":{
                        "name":"main",
                        "characteristics":[
                            {
                                "id":5401,
                                "name":"Culoare",
                                "value":{
                                    "id":7374087,
                                    "value":"Albastru"
                                },
                                "order":0
                            }
                        ]
                    },
                    "offer":{
                        "id":158121094,
                        "price":{
                            "current":100,
                            "is_min":false,
                            "is_max":false,
                            "legal":0,
                            "prefix":"Empty prefix",
                            "suffix":"Empty suffix Lei",
                            "is_visible":true,
                            "discount":{
                                "type":"percent",
                                "absolute":10,
                                "percent":9,
                                "is_special":false,
                                "is_visible":false,
                                "is_restricted_from_view":true,
                                "is_max":false,
                                "label":"Diferen\u021b\u0103:",
                                "labeled_as_discount":false
                            },
                            "currency":{
                                "id":23,
                                "name":{
                                    "default":"RON",
                                    "display":"Lei"
                                }
                            },
                            "net":84.03,
                            "recommended_retail_price":{
                                "amount":0,
                                "is_visible":false,
                                "label":"PRP:",
                                "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                            },
                            "lowest_price_30_days":{
                                "amount":0,
                                "is_visible":false,
                                "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                            },
                            "initial":100
                        },
                        "flags":{
                            "is_main":true,
                            "is_used":false,
                            "is_sales":false,
                            "is_active":true,
                            "has_discount":true,
                            "may_be_ordered":true,
                            "has_ecredit":false,
                            "has_bundles":false,
                            "has_gifts":false,
                            "has_bundle_first":false,
                            "is_self_source":false,
                            "has_warranty":false,
                            "has_badges":false,
                            "is_visible":true,
                            "has_services":false,
                            "has_buyback":false,
                            "has_buyback_v2":false,
                            "has_two_hour_delivery":false,
                            "has_same_day_delivery":false,
                            "has_three_hour_delivery":false,
                            "has_free_delivery":false,
                            "has_delivery_estimate":true,
                            "has_pickup":false,
                            "has_unified_badges":false,
                            "has_loyalty_points":false,
                            "has_banners":false,
                            "is_fulfilment_by_emag":false,
                            "show_legal_price":false,
                            "has_free_return":false,
                            "is_open_package":true,
                            "is_bf":false,
                            "has_campaign_badge":true,
                            "has_visible_badge_border":false,
                            "is_custom_discount":false,
                            "has_unfair_price":false,
                            "is_genius_eligible":true,
                            "genius_eligibility_type":2,
                            "has_courier_6h_delivery":false,
                            "only_in_showroom":false,
                            "is_adult_only":false
                        }
                    },
                    "url":{
                        "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
                },
                "content_no_tags":"",
                "moderated_by":"roxana.badea@emag.ro",
                "rating":5,
                "is_bought":true,
                "votes":0,
                "current_customer_has_voted":false,
                "brand_id":655277,
                "category_id":815,
                "review_characteristics":{
                    "items_count":0
                },
                "offer_id":158121094,
                "client_type":"Review cumparator eMAG",
                "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.",
                "product_doc_id":64743307,
                "product_family_id":4057953
            },
            {
                "id":10105698,
                "content":"TABLETA SE FACE SI MASUTA, USOR DE MONTAT SI DEMONTAT, NE PLACE FOARTE MULT.",
                "user":{
                    "id":8038155,
                    "hash":"aad2fb63101e7818ac9546c6146171aa8038155032",
                    "name":"PIRVU MALINA",
                    "user_avatar":{
                        "initials":"PM",
                        "background_color":"#2196f3"
                    },
                    "nickname":"",
                    "url":{
                        "path":"\/product-feedback\/user-profile\/aad2fb63101e7818ac9546c6146171aa8038155032",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "is_official":false
                },
                "is_active":true,
                "moderation_status":"moderated_accepted",
                "created":"2024-04-03T12:06:39+00:00",
                "modified":"2024-04-03T12:06:39+00:00",
                "published":"2024-04-16T20:41:24+00:00",
                "deleted":"2024-06-11T08:46:49+00:00",
                "report_reason":"",
                "report_reason_description":"",
                "edit_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10105698\/edit",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "view_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10105698",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "type":"REVIEW",
                "title":"Excelent",
                "product":{
                    "id":64743307,
                    "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                    "part_number_key":"DQ1T3KYBM",
                    "image":{
                        "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                        "resized_images":[
                            {
                                "size":"80x80",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                            },
                            {
                                "size":"130x130",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                            },
                            {
                                "size":"300x300",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                            },
                            {
                                "size":"450x450",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                            }
                        ]
                    },
                    "family_characteristics":{
                        "name":"main",
                        "characteristics":[
                            {
                                "id":5401,
                                "name":"Culoare",
                                "value":{
                                    "id":7374087,
                                    "value":"Albastru"
                                },
                                "order":0
                            }
                        ]
                    },
                    "offer":{
                        "id":158121094,
                        "price":{
                            "current":100,
                            "is_min":false,
                            "is_max":false,
                            "legal":0,
                            "prefix":"Empty prefix",
                            "suffix":"Empty suffix Lei",
                            "is_visible":true,
                            "discount":{
                                "type":"percent",
                                "absolute":10,
                                "percent":9,
                                "is_special":false,
                                "is_visible":false,
                                "is_restricted_from_view":true,
                                "is_max":false,
                                "label":"Diferen\u021b\u0103:",
                                "labeled_as_discount":false
                            },
                            "currency":{
                                "id":23,
                                "name":{
                                    "default":"RON",
                                    "display":"Lei"
                                }
                            },
                            "net":84.03,
                            "recommended_retail_price":{
                                "amount":0,
                                "is_visible":false,
                                "label":"PRP:",
                                "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                            },
                            "lowest_price_30_days":{
                                "amount":0,
                                "is_visible":false,
                                "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                            },
                            "initial":100
                        },
                        "flags":{
                            "is_main":true,
                            "is_used":false,
                            "is_sales":false,
                            "is_active":true,
                            "has_discount":true,
                            "may_be_ordered":true,
                            "has_ecredit":false,
                            "has_bundles":false,
                            "has_gifts":false,
                            "has_bundle_first":false,
                            "is_self_source":false,
                            "has_warranty":false,
                            "has_badges":false,
                            "is_visible":true,
                            "has_services":false,
                            "has_buyback":false,
                            "has_buyback_v2":false,
                            "has_two_hour_delivery":false,
                            "has_same_day_delivery":false,
                            "has_three_hour_delivery":false,
                            "has_free_delivery":false,
                            "has_delivery_estimate":true,
                            "has_pickup":false,
                            "has_unified_badges":false,
                            "has_loyalty_points":false,
                            "has_banners":false,
                            "is_fulfilment_by_emag":false,
                            "show_legal_price":false,
                            "has_free_return":false,
                            "is_open_package":true,
                            "is_bf":false,
                            "has_campaign_badge":true,
                            "has_visible_badge_border":false,
                            "is_custom_discount":false,
                            "has_unfair_price":false,
                            "is_genius_eligible":true,
                            "genius_eligibility_type":2,
                            "has_courier_6h_delivery":false,
                            "only_in_showroom":false,
                            "is_adult_only":false
                        }
                    },
                    "url":{
                        "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
                },
                "content_no_tags":"TABLETA SE FACE SI MASUTA, USOR DE MONTAT SI DEMONTAT, NE PLACE FOARTE MULT.",
                "moderated_by":"valentin.stan@emag.ro",
                "rating":5,
                "is_bought":true,
                "votes":0,
                "comments":[
                    {
                        "id":10422838,
                        "content":"Bun\u0103 Malina,\u003Cbr \/\u003E \u003Cbr \/\u003E Ne bucur\u0103m s\u0103 auzim c\u0103 varianta Albastru a tablei de desen magnetice \u00ee\u021bi place foarte mult \u0219i c\u0103 o g\u0103se\u0219ti u\u0219or de montat \u0219i demontat, func\u021bion\u00e2nd \u0219i ca m\u0103su\u021b\u0103.\u003Cbr \/\u003E \u003Cbr \/\u003E Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\u003Cbr \/\u003E \u003Cbr \/\u003E Echipa Innovators",
                        "user":{
                            "id":105498146,
                            "hash":"dfadb97cd35e536d23646c233faf77c6105498146032",
                            "name":"The Innovators",
                            "user_avatar":{
                                "initials":"TI",
                                "background_color":"#009688"
                            },
                            "nickname":"",
                            "url":{
                                "path":"\/product-feedback\/user-profile\/dfadb97cd35e536d23646c233faf77c6105498146032",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "is_official":true
                        },
                        "is_active":true,
                        "moderation_status":"moderated_accepted",
                        "created":"2024-06-10T15:05:47+03:00",
                        "modified":"2024-06-10T15:05:47+03:00",
                        "published":"2024-06-11T08:46:49+03:00",
                        "deleted":"",
                        "report_reason":"",
                        "report_reason_description":"",
                        "edit_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10105698\/comment\/10422838\/edit",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "view_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/10105698\/comment\/10422838",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "type":"COMMENT",
                        "product":{
                            "id":64743307,
                            "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                            "url":{
                                "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "part_number_key":"DQ1T3KYBM"
                        },
                        "content_no_tags":"Bun\u0103 Malina,\n \n Ne bucur\u0103m s\u0103 auzim c\u0103 varianta Albastru a tablei de desen magnetice \u00ee\u021bi place foarte mult \u0219i c\u0103 o g\u0103se\u0219ti u\u0219or de montat \u0219i demontat, func\u021bion\u00e2nd \u0219i ca m\u0103su\u021b\u0103.\n \n Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\n \n Echipa Innovators",
                        "moderated_by":"cerasela.maxim@emag.ro",
                        "parent_id":10105698,
                        "is_official":true
                    }
                ],
                "current_customer_has_voted":false,
                "brand_id":655277,
                "category_id":815,
                "review_characteristics":{
                    "items_count":0
                },
                "offer_id":158121094,
                "client_type":"Review cumparator eMAG",
                "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.",
                "product_doc_id":64743307,
                "product_family_id":4057953
            },
            {
                "id":9696871,
                "content":"Foarte frumoas\u0103 t\u0103bli\u021ba \u0219i de calitate, este rezistent\u0103, am f\u0103cut testul (b\u0103ie\u021belul nu eu) sa urcat \u00een picioare pe ea \u0219i a rezistat \u0219i \u00eenc\u0103 mai rezist\u0103 la 18 kg\ud83d\ude01 foarte mul\u021bumit\u0103",
                "user":{
                    "id":106338201,
                    "hash":"9e4f518c9fb5b0a58bade8d7323ee468106338201032",
                    "name":"Alexandra Ioana",
                    "user_avatar":{
                        "initials":"AI",
                        "background_color":"#e91e63"
                    },
                    "nickname":"",
                    "url":{
                        "path":"\/product-feedback\/user-profile\/9e4f518c9fb5b0a58bade8d7323ee468106338201032",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "is_official":false
                },
                "is_active":true,
                "moderation_status":"moderated_accepted",
                "created":"2024-01-09T17:35:15+00:00",
                "modified":"2024-02-05T18:49:38+00:00",
                "published":"2024-02-08T15:24:31+00:00",
                "deleted":"2024-06-11T08:46:48+00:00",
                "report_reason":"",
                "report_reason_description":"",
                "edit_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/9696871\/edit",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "view_url":{
                    "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/9696871",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                },
                "type":"REVIEW",
                "title":"Foarte multumita",
                "product":{
                    "id":64743307,
                    "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru","part_number_key":"DQ1T3KYBM",
                    "image":{
                        "original":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg",
                        "resized_images":[
                            {
                                "size":"80x80",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=80\u0026height=80\u0026hash=D3D0ED894B251B3FCE14B3FED82CD1CC"
                            },
                            {
                                "size":"130x130",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=100\u0026height=100\u0026hash=6E720C8841EC6CF9423A538646A1716C"
                            },
                            {
                                "size":"300x300",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=300\u0026height=300\u0026hash=C3EC25DC506C5AAD8EF1FD4F6F596565"
                            },
                            {
                                "size":"450x450",
                                "url":"https:\/\/s13emagst.akamaized.net\/products\/64744\/64743307\/images\/res_d9c05bab361bd2cc2753cb9e2abfa3d0.jpg?width=450\u0026height=450\u0026hash=4F4B4ACCA7FB380674702BCC83220D8A"
                            }
                        ]
                    },
                    "family_characteristics":{
                        "name":"main",
                        "characteristics":[
                            {
                                "id":5401,
                                "name":"Culoare",
                                "value":{
                                    "id":7374087,
                                    "value":"Albastru"
                                },
                                "order":0
                            }
                        ]
                    },
                    "offer":{
                        "id":158121094,
                        "price":{
                            "current":100,
                            "is_min":false,
                            "is_max":false,
                            "legal":0,
                            "prefix":"Empty prefix",
                            "suffix":"Empty suffix Lei",
                            "is_visible":true,
                            "discount":{
                                "type":"percent",
                                "absolute":10,
                                "percent":9,
                                "is_special":false,
                                "is_visible":false,
                                "is_restricted_from_view":true,
                                "is_max":false,
                                "label":"Diferen\u021b\u0103:",
                                "labeled_as_discount":false
                            },
                            "currency":{
                                "id":23,
                                "name":{
                                    "default":"RON",
                                    "display":"Lei"
                                }
                            },
                            "net":84.03,
                            "recommended_retail_price":{
                                "amount":0,
                                "is_visible":false,
                                "label":"PRP:",
                                "tooltip":"Acesta este Pre\u021bul Recomandat de Produc\u0103tor. Pre\u021bul de v\u00e2nzare al produsului este afi\u0219at mai jos."
                            },
                            "lowest_price_30_days":{
                                "amount":0,
                                "is_visible":false,
                                "tooltip":"Pre\u021bul t\u0103iat este cel mai mic pre\u021b la care a fost v\u00e2ndut produsul \u00een ultimele 30 zile."
                            },
                            "initial":100
                        },
                        "flags":{
                            "is_main":true,
                            "is_used":false,
                            "is_sales":false,
                            "is_active":true,
                            "has_discount":true,
                            "may_be_ordered":true,
                            "has_ecredit":false,
                            "has_bundles":false,
                            "has_gifts":false,
                            "has_bundle_first":false,
                            "is_self_source":false,
                            "has_warranty":false,
                            "has_badges":false,
                            "is_visible":true,
                            "has_services":false,
                            "has_buyback":false,
                            "has_buyback_v2":false,
                            "has_two_hour_delivery":false,
                            "has_same_day_delivery":false,
                            "has_three_hour_delivery":false,
                            "has_free_delivery":false,
                            "has_delivery_estimate":true,
                            "has_pickup":false,
                            "has_unified_badges":false,
                            "has_loyalty_points":false,
                            "has_banners":false,
                            "is_fulfilment_by_emag":false,
                            "show_legal_price":false,
                            "has_free_return":false,
                            "is_open_package":true,
                            "is_bf":false,
                            "has_campaign_badge":true,
                            "has_visible_badge_border":false,
                            "is_custom_discount":false,
                            "has_unfair_price":false,
                            "is_genius_eligible":true,
                            "genius_eligibility_type":2,
                            "has_courier_6h_delivery":false,
                            "only_in_showroom":false,
                            "is_adult_only":false
                        }
                    },
                    "url":{
                        "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                        "desktop_base":"https:\/\/www.emag.ro",
                        "mobile_base":"https:\/\/www.emag.ro"
                    },
                    "sef_name":"tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl"
                },
                "content_no_tags":"Foarte frumoas\u0103 t\u0103bli\u021ba \u0219i de calitate, este rezistent\u0103, am f\u0103cut testul (b\u0103ie\u021belul nu eu) sa urcat \u00een picioare pe ea \u0219i a rezistat \u0219i \u00eenc\u0103 mai rezist\u0103 la 18 kg\ud83d\ude01 foarte mul\u021bumit\u0103",
                "moderated_by":"narcisa.duma@emag.ro",
                "rating":5,
                "is_bought":true,
                "votes":0,
                "comments":[
                    {
                        "id":10422840,
                        "content":"Bun\u0103 Alexandra Ioana,\u003Cbr \/\u003E \u003Cbr \/\u003E Ne bucur\u0103m s\u0103 auzim c\u0103 e\u0219ti foarte mul\u021bumit\u0103 de varianta Albastru a tablei de desen magnetice \u0219i c\u0103 aceasta este frumoas\u0103, de calitate \u0219i rezistent\u0103. E minunat s\u0103 \u0219tim c\u0103 a trecut cu brio testul rezisten\u021bei efectuat de b\u0103ie\u021belul t\u0103u!\u003Cbr \/\u003E \u003Cbr \/\u003E Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\u003Cbr \/\u003E \u003Cbr \/\u003E Echipa Innovators",
                        "user":{
                            "id":105498146,
                            "hash":"dfadb97cd35e536d23646c233faf77c6105498146032",
                            "name":"The Innovators",
                            "user_avatar":{
                                "initials":"TI",
                                "background_color":"#009688"
                            },
                            "nickname":"",
                            "url":{
                                "path":"\/product-feedback\/user-profile\/dfadb97cd35e536d23646c233faf77c6105498146032",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "is_official":true
                        },
                        "is_active":true,
                        "moderation_status":"moderated_accepted",
                        "created":"2024-06-10T15:06:21+03:00",
                        "modified":"2024-06-10T15:06:21+03:00",
                        "published":"2024-06-11T08:46:48+03:00",
                        "deleted":"",
                        "report_reason":"",
                        "report_reason_description":"",
                        "edit_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/9696871\/comment\/10422840\/edit",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "view_url":{
                            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/9696871\/comment\/10422840",
                            "desktop_base":"https:\/\/www.emag.ro",
                            "mobile_base":"https:\/\/www.emag.ro"
                        },
                        "type":"COMMENT",
                        "product":{
                            "id":64743307,
                            "name":"Tabla de desen magnetica pentru copii, masuta de desenat, jucarie educative, 4 culori, 25 cm, Albastru",
                            "url":{
                                "path":"\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/",
                                "desktop_base":"https:\/\/www.emag.ro",
                                "mobile_base":"https:\/\/www.emag.ro"
                            },
                            "part_number_key":"DQ1T3KYBM"
                        },
                        "content_no_tags":"Bun\u0103 Alexandra Ioana,\n \n Ne bucur\u0103m s\u0103 auzim c\u0103 e\u0219ti foarte mul\u021bumit\u0103 de varianta Albastru a tablei de desen magnetice \u0219i c\u0103 aceasta este frumoas\u0103, de calitate \u0219i rezistent\u0103. E minunat s\u0103 \u0219tim c\u0103 a trecut cu brio testul rezisten\u021bei efectuat de b\u0103ie\u021belul t\u0103u!\n \n Pentru orice \u00eentreb\u0103ri sau asisten\u021b\u0103, echipa noastr\u0103 este gata s\u0103 te ajute \u00een orice moment. Ne po\u021bi contacta prin e-mail la clienti.innovators@gmail.com sau telefonic la num\u0103rul 0 (770) 915 322. Suntem disponibili de luni p\u00e2n\u0103 vineri, \u00eentre orele 09:00 \u0219i 17:00.\n \n Echipa Innovators",
                        "moderated_by":"cerasela.maxim@emag.ro",
                        "parent_id":9696871,
                        "is_official":true
                    }
                ],
                "current_customer_has_voted":false,
                "brand_id":655277,
                "category_id":815,
                "review_characteristics":{
                    "items_count":0
                },
                "offer_id":158121094,
                "client_type":"Review cumparator eMAG",
                "client_type_info":"Review-ul este publicat de catre un Cump\u0103r\u0103tor care a achizitionat Bunul\/Serviciul prin platforma eMAG.",
                "product_doc_id":64743307,
                "product_family_id":4057953
            }
        ],
        "rating_distribution":{
            "1":0,
            "2":0,
            "3":0,
            "4":0,
            "5":5
        },
        "add_url":{
            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/review\/add",
            "desktop_base":"https:\/\/www.emag.ro",
            "mobile_base":"https:\/\/www.emag.ro"
        },
        "view_url":{
            "path":"\/product-feedback\/tabla-de-desen-magnetica-pentru-copii-masuta-de-desenat-jucarie-educative-4-culori-25-cm-albastru-inv-td101-bl\/pd\/DQ1T3KYBM\/reviews",
            "desktop_base":"https:\/\/www.emag.ro",
            "mobile_base":"https:\/\/www.emag.ro"
        },
        "family_id":4057953,
        "sort_options":[
            {
                "name":"created",
                "direction":"desc",
                "placeholder":"Cele mai noi",
                "isSelected":false,
                "isDefault":true
            },
            {
                "name":"votes",
                "direction":"desc",
                "placeholder":"Cele mai populare",
                "isSelected":true,
                "isDefault":false
            }
        ],
        "positive_rating_percentage":0,
        "bought_count":5,
        "bought_count_filter":"Doar reviews cumparatori eMAG",
        "bought_count_message":"Reviews cumparatori eMAG",
        "positive_rating_percentage_message":"clienti eMAG recomanda produsul"
    },
    "meta":{
        "default":{
            "title":{
                "id":6625,
                "text":"eMAG.ro - C\u0103utarea nu se opre\u0219te niciodat\u0103"
            },
            "description":{
                "id":6626,
                "text":"Ai libertatea sa alegi din milioane de produse IT, electronice si electrocasnice, gadgeturi, jucarii, imbracaminte si incaltaminte la Super Pret sau cu plata in rate. Livrare rapida la easybox, Instant Money Back la retur, garantia produselor."
            },
            "keywords":{
                "id":0,
                "text":"emag.ro, c\u0103utarea, opre\u0219te, niciodat\u0103"
            },
            "canonical":{
                "id":0,
                "text":"\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list",
                "url":{
                    "path":"\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                }
            },
            "deeplinks":{
                "property":[
                    {
                        "type":"al:ios:url",
                        "text":"emag:\/\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"al:ios:app_store_id",
                        "text":"935571974"
                    },
                    {
                        "type":"al:ios:app_name",
                        "text":"eMAG"
                    },
                    {
                        "type":"al:android:url",
                        "text":"emag:\/\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"al:android:app_name",
                        "text":"eMAG"
                    },
                    {
                        "type":"al:android:package","text":"ro.emag.android"
                    }
                ],
                "alternate":[
                    {
                        "type":"0",
                        "text":"android-app:\/\/ro.emag.android\/emag\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"1",
                        "text":"ios-app:\/\/935571974\/emag\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    }
                ]
            }
        },
        "custom":{
            "title":{
                "id":6625,
                "text":"eMAG.ro - C\u0103utarea nu se opre\u0219te niciodat\u0103"
            },
            "description":{
                "id":6626,
                "text":"Ai libertatea sa alegi din milioane de produse IT, electronice si electrocasnice, gadgeturi, jucarii, imbracaminte si incaltaminte la Super Pret sau cu plata in rate. Livrare rapida la easybox, Instant Money Back la retur, garantia produselor."
            },
            "keywords":{
                "id":0,
                "text":"emag.ro, c\u0103utarea, opre\u0219te, niciodat\u0103"
            },
            "canonical":{
                "id":0,
                "text":"\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list",
                "url":{
                    "path":"\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list",
                    "desktop_base":"https:\/\/www.emag.ro",
                    "mobile_base":"https:\/\/www.emag.ro"
                }
            },
            "deeplinks":{
                "property":[
                    {
                        "type":"al:ios:url",
                        "text":"emag:\/\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"al:ios:app_store_id",
                        "text":"935571974"
                    },
                    {
                        "type":"al:ios:app_name",
                        "text":"eMAG"
                    },
                    {
                        "type":"al:android:url",
                        "text":"emag:\/\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"al:android:app_name",
                        "text":"eMAG"
                    },
                    {
                        "type":"al:android:package",
                        "text":"ro.emag.android"
                    }
                ],
                "alternate":[
                    {
                        "type":"0",
                        "text":"android-app:\/\/ro.emag.android\/emag\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    },
                    {
                        "type":"1",
                        "text":"ios-app:\/\/935571974\/emag\/webview?url=\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list"
                    }
                ]
            }
        }
    },
    "url":"\/product-feedback\/739062590\/pd\/DQ1T3KYBM\/reviews\/list",
    "response":{
        "code":200
    },
    "pageType_google":"other",
    "page_type":"list_review"
}