from sqlalchemy import Column, Integer, String, Text, Numeric, Boolean, VARCHAR, JSON
from app.database import Base

class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    product_name = Column(Text, nullable=True)
    model_name = Column(Text, nullable=True)
    sku = Column(Text, nullable=True)
    price = Column(Numeric(12, 4), nullable=True)
    image_link = Column(Text, nullable=True)
    barcode_title = Column(Text, nullable=True)
    masterbox_title = Column(Text, nullable=True)
    link_address_1688 = Column(Text, nullable=True)
    price_1688 = Column(Numeric(12, 4), nullable=True)
    variation_name_1688 = Column(Text, nullable=True)
    pcs_ctn = Column(Text, nullable=True)
    weight = Column(Numeric(12, 6), nullable=True)
    volumetric_weight = Column(Numeric(12, 6), nullable=True)
    dimensions = Column(Text, nullable=True)
    supplier_id = Column(Integer, nullable=True)
    english_name = Column(Text, nullable=True)
    romanian_name = Column(Text, nullable=True)
    material_name_en = Column(Text, nullable=True)
    material_name_ro = Column(Text, nullable=True)
    hs_code = Column(Text, nullable=True)
    battery = Column(Boolean, nullable=True)
    default_usage = Column(Text, nullable=True)
    production_time = Column(Numeric(12, 6), nullable=True)
    discontinued = Column(Boolean, nullable=True)
    stock = Column(Integer, nullable=True)



    # admin_user = Column(Text, nullable=True)
    # part_number_key = Column(Text, nullable=True)
    # brand_name = Column(Text, nullable=True)
    # buy_button_rank = Column(Integer, nullable=True)
    # category_id = Column(Integer, nullable=True)
    # brand = Column(Text, nullable=True)
    # name = Column(Text, nullable=True)
    # part_number = Column(Text, nullable=True)
    # sale_price = Column(Numeric(16, 4), nullable=True)
    # currency = Column(VARCHAR(10), nullable=True)
    # description = Column(Text, nullable=True)
    # url = Column(Text, nullable=True)
    # warranty = Column(Integer, nullable=True)
    # general_stock = Column(Integer, nullable=True)
    
    # status = Column(Integer, nullable=True)
    # recommended_price = Column(Numeric(16, 4), nullable=True)
    # images = Column(Text, nullable=True)
    # attachments = Column(Text, nullable=True)
    # vat_id = Column(Integer, nullable=True)
    # family = Column(Text, nullable=True)
    # reversible_vat_charging = Column(Boolean, nullable=True)
    # min_sale_price = Column(Numeric(16, 4), nullable=True)
    # max_sale_price = Column(Numeric(16, 4), nullable=True)
    # offer_details = Column(Text, nullable=True)
    # availability = Column(Text, nullable=True)
    # stock = Column(Integer, nullable=True)
    # handling_time = Column(Text, nullable=True)
    # ean = Column(Text, nullable=True)
    # commission = Column(Numeric(16, 4), nullable=True)
    # validation_status = Column(Text, nullable=True)
    # translation_validation_status = Column(Text, nullable=True)
    # offer_validation_status = Column(Text, nullable=True)
    # auto_translated = Column(Integer, nullable=True)
    # ownership = Column(Boolean, nullable=True)
    # best_offer_sale_price = Column(Numeric(16, 4), nullable=True)
    # best_offer_recommended_price = Column(Numeric(16, 4), nullable=True)
    # number_of_offers = Column(Integer, nullable=True)
    # genius_eligibility = Column(Integer, nullable=True)
    # recyclewarranties = Column(Integer, nullable=True)
